# Decision Record Template
# Copy this file to DECISION-YYYY-MM-DD-NNN.yaml and fill in the details
#
# Decision records document WHY decisions were made during AI-assisted development.
# They enable audit, review, learning, and accountability.

decision_id: "DECISION-YYYY-MM-DD-NNN"
timestamp: "YYYY-MM-DDTHH:MM:SSZ"
ai_model: "claude-opus-4-5-20251101"
session_id: ""  # From .claude/projects/ session file

# ============================================================================
# SUMMARY
# ============================================================================
# One-line description of what was decided
summary: ""

# ============================================================================
# TRIGGER
# ============================================================================
# What prompted this decision?
trigger:
  type: "user_request"  # user_request | error_encountered | optimization | refactor
  content: ""           # The actual request or error message
  context: ""           # Additional context that informed the decision

# ============================================================================
# ALTERNATIVES CONSIDERED
# ============================================================================
# Document at least 2 alternatives, even if one was obvious
alternatives:
  - option: "Option A description"
    pros:
      - "Pro 1"
      - "Pro 2"
    cons:
      - "Con 1"
    selected: false
    rejected_reason: "Why this option was not chosen"

  - option: "Option B description"
    pros:
      - "Pro 1"
    cons:
      - "Con 1"
    selected: true
    selected_reason: "Why this option was chosen"

# ============================================================================
# IMPACT ASSESSMENT
# ============================================================================
impact:
  files_modified: 0
  files_created: 0
  files_deleted: 0
  lines_added: 0
  lines_removed: 0
  breaking_changes: false
  deprecations_added: false
  new_dependencies: []
  tests_affected: 0

# ============================================================================
# VERIFICATION
# ============================================================================
# What was done to verify the decision was correct?
verification:
  - action: "Ran test suite"
    result: "All tests pass"
  - action: "Manual testing"
    result: "Feature works as expected"

# ============================================================================
# RISK ASSESSMENT
# ============================================================================
risks:
  - risk: "Description of potential risk"
    mitigation: "How the risk is mitigated"
    severity: "low"  # low | medium | high | critical
    likelihood: "low"  # low | medium | high

# ============================================================================
# REFERENCES
# ============================================================================
references:
  - type: "documentation"  # documentation | code | issue | pr | external
    path: ""
    section: ""
    url: ""  # For external references

# ============================================================================
# REVIEW
# ============================================================================
# Filled in during human review
review:
  status: "pending"  # pending | approved | rejected | changes_requested
  reviewer: ""
  reviewed_at: ""
  comments: ""
  modifications_required: []

# ============================================================================
# FOLLOW-UP
# ============================================================================
# Any actions needed after this decision
follow_up:
  - action: ""
    owner: ""
    due_date: ""
    status: "pending"
