#!/usr/bin/env python
"""Write the domain-flow ceilings of every generated KPU core (graphs#269 6.4).

The ceilings are computed by ``graphs.estimation.soc.domainflow`` from each
SKU's own geometry, clock and DRAM bandwidth, on the benchmark suite's
shapes. This writes them to ``soc_designs/ceilings/`` so they are reviewable
and diff when the model or a SKU changes.

They are **ceilings, not efficiencies**: deliberately not an
``EfficiencyTable``, and not in ``soc_designs/efficiency/``, so no analysis
can price a stage with them.

Usage:
    python tools/generate_kpu_ceilings.py          # write
    python tools/generate_kpu_ceilings.py --check  # fail if a file differs
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Optional

import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from embodied_schemas import load_compute_products  # noqa: E402

from graphs.estimation.soc.domainflow import fabric_ceilings  # noqa: E402
from graphs.hardware.kpu_sku_generator import input_spec_from_compute_product  # noqa: E402
from graphs.hardware.soc.kpu_cores import KPU_CORES  # noqa: E402

CEILING_DIR = REPO / "soc_designs" / "ceilings"


def document(sku: str) -> dict:
    products = load_compute_products()
    spec = input_spec_from_compute_product(products[sku])
    payload = fabric_ceilings(spec).to_dict()
    payload["kind"] = "kpu_domainflow_ceilings/1"
    payload["notes"] = (
        "Generated by tools/generate_kpu_ceilings.py; do not edit by hand. Each value is an "
        "UPPER BOUND on what the fabric could sustain on that kernel: the least of the "
        "wavefront schedule, the compulsory DRAM traffic and, where the tile class states an "
        "interconnect, operand delivery. A ceiling is not an efficiency -- it says what cannot "
        "be exceeded, never what will be achieved -- so this is not an efficiency table and no "
        "analysis prices a stage with it.")
    return payload


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="Compare with the files on disk instead of writing")
    args = parser.parse_args(argv)

    CEILING_DIR.mkdir(parents=True, exist_ok=True)
    status = 0
    for template, (sku, _core) in sorted(KPU_CORES.items()):
        payload = document(sku)
        out = CEILING_DIR / f"{template}.yaml"
        if args.check:
            if not out.exists() or yaml.safe_load(out.read_text()) != payload:
                print(f"FAIL: {out} differs from the model; regenerate it")
                status = 1
            else:
                print(f"OK: {out}")
            continue
        out.write_text(yaml.safe_dump(payload, sort_keys=False, width=100))
        print(f"wrote {out} ({len(payload['ceilings'])} ceilings)")
    return status


if __name__ == "__main__":
    sys.exit(main())
