# Conv2d Benchmark Specifications - Batched Operations
# These cover batch inference scenarios

# Batched standard 3x3 convolutions
---
name: conv2d_3x3_64_56x56_batch4
description: Batched 3x3 conv - 4 images
category: microbenchmark
tags: [conv2d, batched, resnet]
batch_size: 4
in_channels: 64
out_channels: 64
height: 56
width: 56
kernel_size: 3
stride: 1
padding: 1
precisions: [fp32, fp16]
devices: [auto]

---
name: conv2d_3x3_64_56x56_batch8
description: Batched 3x3 conv - 8 images
category: microbenchmark
tags: [conv2d, batched, resnet]
batch_size: 8
in_channels: 64
out_channels: 64
height: 56
width: 56
kernel_size: 3
stride: 1
padding: 1
precisions: [fp32, fp16]
devices: [auto]

---
name: conv2d_3x3_64_56x56_batch16
description: Batched 3x3 conv - 16 images
category: microbenchmark
tags: [conv2d, batched, resnet]
batch_size: 16
in_channels: 64
out_channels: 64
height: 56
width: 56
kernel_size: 3
stride: 1
padding: 1
precisions: [fp16]
devices: [auto]

---
name: conv2d_3x3_128_28x28_batch8
description: Batched mid-stage 3x3 conv
category: microbenchmark
tags: [conv2d, batched, resnet]
batch_size: 8
in_channels: 128
out_channels: 128
height: 28
width: 28
kernel_size: 3
stride: 1
padding: 1
precisions: [fp32, fp16]
devices: [auto]

---
name: conv2d_3x3_256_14x14_batch8
description: Batched late-stage 3x3 conv
category: microbenchmark
tags: [conv2d, batched, resnet]
batch_size: 8
in_channels: 256
out_channels: 256
height: 14
width: 14
kernel_size: 3
stride: 1
padding: 1
precisions: [fp32, fp16]
devices: [auto]

# Batched depthwise
---
name: conv2d_dw_3x3_64_56x56_batch4
description: Batched depthwise 3x3 conv
category: microbenchmark
tags: [conv2d, depthwise, batched, mobilenet]
batch_size: 4
in_channels: 64
out_channels: 64
height: 56
width: 56
kernel_size: 3
stride: 1
padding: 1
groups: 64
precisions: [fp32, fp16]
devices: [auto]

---
name: conv2d_dw_3x3_128_28x28_batch8
description: Batched depthwise mid-stage
category: microbenchmark
tags: [conv2d, depthwise, batched, mobilenet]
batch_size: 8
in_channels: 128
out_channels: 128
height: 28
width: 28
kernel_size: 3
stride: 1
padding: 1
groups: 128
precisions: [fp32, fp16]
devices: [auto]

# Batched pointwise
---
name: conv2d_1x1_64_to_256_batch8
description: Batched pointwise expansion
category: microbenchmark
tags: [conv2d, pointwise, batched]
batch_size: 8
in_channels: 64
out_channels: 256
height: 56
width: 56
kernel_size: 1
stride: 1
padding: 0
precisions: [fp32, fp16]
devices: [auto]

---
name: conv2d_1x1_256_to_64_batch8
description: Batched pointwise projection
category: microbenchmark
tags: [conv2d, pointwise, batched]
batch_size: 8
in_channels: 256
out_channels: 64
height: 56
width: 56
kernel_size: 1
stride: 1
padding: 0
precisions: [fp32, fp16]
devices: [auto]
